spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
server:
  port: 8080

fraud:
  check:
    interval: PT5H
    enabled: true
    threshold: 1000

java:
  security:
    debug: providers
    providers: debug